# 四层架构 : controller -> facade -> service -> repository
package:
  path: # 绝对路径, 不传默认生成在当前项目 resources/target 下
    controller: ""
    facade: ""
    service: ""
    manager: ""
    repository: ""
    convert: ""
    po: ""
    to: ""
